package frc.robot.subsystems.arm;

public enum ArmState {
    STARTING,
    BALLPICKUP,
    BALLSTATION,
    BALLGROUND,
    HATCHSTATION,
    ROCKETBALL1,
    ROCKETBALL2,
    ROCKETBALL3,
    CARGOBALL1,
    CARGOBALL2,
    CARGOBALL3,
    CARGOHATCH,
    ROCKETHATCH1,
    ROCKETHATCH2,
    ROCKETHATCH3
}

